name: CI
on:
    push:
        branches: [ubuntu]
    workflow_dispatch:
jobs:
    build-backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - run: npm install
            - run: npm run build
            - run: npm run deploy
